### ISSUE TITLE
Front end to-do

### ISSUE THREAD

**Issue by carlvitzthum** [4dn-dcic/fourfront#170]
Based on meetings with Nils' @ngehlenborg 

**Navbar**
- [ ] Add icon to user login
- [ ] Change login popup from "Please wait..."

**Search**
- [ ] Give more informative search item results, starting with experiment, biosource, and experiment set (see issue #169 )
- [ ] If searching multiple types, use tabs (?) to direct to individual searches
- [x] Add titles to search pages with number of displayed results (e.g. showing x of y results)
- [ ] Get public opinion to ensure usability

**Facets**
- [ ] Change highlighting to bold
- [ ] Indent facet entries from left, add open or close icon there

**Calculated properties**
- [x] Concatenate treatments/modifications, using calculated properties in biosamples

**Individual object views**
- [ ] Create them for experiment, biosource, and experiment set
- [ ] Get public opinion

**General**
- [ ] Change iconset
